---
swagger: '2.0'
info:
  version: 1.0.0
  title: Minimum API
  description: Sample API
  x-wap-package-name: minimum
paths:
  /users/{userId}:
    get:
      parameters:
        - name: Authorization
          in: header
          type: string
        - $ref: '#/parameters/X-Forwarded-For'
        - name: userId
          in: path
          type: string
          required: true
        - name: limit
          in: query
          type: integer
      responses:
        200:
          description: OK
          headers:
            ETag:
              type: string
          schema:
            type: object
            properties:
              userId:
                type: string
              role:
                type: string
parameters:
  X-Forwarded-For:
    name: X-Forwarded-For
    description: この API は、 IP アドレスによる匿名によるアクセスが可能です。
    in: header